name: dev_coding_test_calvin
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # state management
  stacked: ^2.1.7
  stacked_services: ^0.8.6
  stacked_hooks: ^0.2.0
  flutter_hooks: 

  # navigation
  auto_route: ^2.2.0

  # inversion of control
  get_it: ^7.1.3
  injectable: ^1.4.1
  
  # misc
  logger: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  build_runner: ^2.0.4
  auto_route_generator: ^2.1.0
  injectable_generator: ^1.4.1
  flutter_launcher_icons: ^0.9.0

  # linting
  flutter_lints: ^1.0.0

  flutter_screenutil: ^5.0.0+2
  horizontal_data_table: ^3.4.2
  easy_localization: ^3.0.0
  collection: ^1.15.0
  sticky_headers: ^0.2.0
  
flutter:
  uses-material-design: true

# Assets Example
  assets:
    - assets/Input.txt
#    - assets/images/
#
# Fonts Example
#  fonts:
#    - family: Open Sans
#      fonts:
#        - asset: assets/fonts/OpenSans-Italic.ttf
#          style: italic
#        - asset: assets/fonts/OpenSans-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/OpenSans-ExtraBold.ttf
#          weight: 800
#        - asset: assets/fonts/OpenSans-Light.ttf
#          weight: 300
#        - asset: assets/fonts/OpenSans-Regular.ttf
#          weight: 400